/**
 * Utility function to map stage names to artifact types
 * Some stages generate multiple artifacts; this function returns the primary one.
 */

export const stageToArtifact = (stageName: string): string => {
  const mapping: Record<string, string> = {
    'project-setup': 'ProjectContext',
    'problem-framing': 'ProblemFraming', // Note: also generates ConceptModel
    'research-questions': 'ResearchQuestionSet',
    'search-concept-expansion': 'SearchConceptBlocks',
    'database-query-plan': 'DatabaseQueryPlan',
    'screening-criteria': 'ScreeningCriteria',
    'query-execution': 'SearchResults',
    'strategy-export': 'StrategyExportBundle',
  };

  return mapping[stageName] || stageName;
};

/**
 * Get all artifacts generated by a stage
 * Some stages generate multiple artifacts (e.g., problem-framing generates both ProblemFraming and ConceptModel)
 */
export const stageToArtifacts = (stageName: string): string[] => {
  const mapping: Record<string, string[]> = {
    'project-setup': ['ProjectContext'],
    'problem-framing': ['ProblemFraming', 'ConceptModel'],
    'research-questions': ['ResearchQuestionSet'],
    'search-concept-expansion': ['SearchConceptBlocks'],
    'database-query-plan': ['DatabaseQueryPlan'],
    'screening-criteria': ['ScreeningCriteria'],
    'query-execution': ['SearchResults'],
    'strategy-export': ['StrategyExportBundle'],
  };

  return mapping[stageName] || [stageName];
};

