"""Core data models (artifacts) for the HITL research-strategy pipeline.

These models are UI-agnostic and represent the domain objects that flow through
the pipeline stages.
"""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class ApprovalStatus(str, Enum):
    """Status of an artifact in the HITL approval workflow."""
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    APPROVED_WITH_NOTES = "APPROVED_WITH_NOTES"
    REQUIRES_REVISION = "REQUIRES_REVISION"


@dataclass
class ModelMetadata:
    """Metadata tracking how an artifact was generated by LLM/SLM."""
    model_name: str
    mode: str  # e.g., "llm", "slm", "hybrid"
    prompt_version: Optional[str] = None
    generated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    notes: Optional[str] = None


@dataclass
class ProjectContext:
    """Project-level metadata and initial framing."""
    id: str
    title: str
    short_description: str
    discipline: Optional[str] = None
    subfield: Optional[str] = None
    application_area: Optional[str] = None
    constraints: Dict[str, Any] = field(default_factory=dict)
    initial_keywords: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class ProblemFraming:
    """Structured problem statement, goals, and scope."""
    project_id: str
    problem_statement: str
    goals: List[str]
    scope_in: List[str] = field(default_factory=list)
    scope_out: List[str] = field(default_factory=list)
    stakeholders: List[str] = field(default_factory=list)
    research_gap: Optional[str] = None  # What's missing in current literature
    critique_report: Optional[str] = None  # AI critique + validation report
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class Concept:
    """A key concept extracted from the problem framing."""
    id: str
    label: str
    description: str
    type: str  # e.g., population, intervention, outcome, method, context


@dataclass
class Relation:
    """A relationship between two concepts."""
    id: str
    source_id: str
    target_id: str
    relation_type: str
    description: Optional[str] = None


@dataclass
class ConceptModel:
    """Collection of concepts and their relationships."""
    project_id: str
    concepts: List[Concept] = field(default_factory=list)
    relations: List[Relation] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class ResearchQuestion:
    """A single research question with metadata."""
    id: str
    text: str
    type: str  # descriptive, explanatory, evaluative, design, etc.
    linked_concept_ids: List[str] = field(default_factory=list)
    priority: str = "must_have"  # or "nice_to_have"
    methodological_lens: Optional[str] = None


@dataclass
class ResearchQuestionSet:
    """Collection of research questions for the project."""
    project_id: str
    questions: List[ResearchQuestion] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class SearchConceptBlock:
    """A group of synonymous/related terms for one conceptual dimension."""
    id: str
    label: str
    description: Optional[str] = None
    terms_included: List[str] = field(default_factory=list)
    terms_excluded: List[str] = field(default_factory=list)


@dataclass
class SearchConceptBlocks:
    """Collection of search concept blocks."""
    project_id: str
    blocks: List[SearchConceptBlock] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class DatabaseQuery:
    """A database-specific search query."""
    id: str
    database_name: str
    query_blocks: List[str] = field(default_factory=list)  # references to SearchConceptBlock ids
    boolean_query_string: str = ""
    notes: Optional[str] = None
    hit_count_estimate: Optional[int] = None
    complexity_analysis: Optional[dict] = None  # Complexity metrics and guidance


@dataclass
class DatabaseQueryPlan:
    """Collection of database queries for the search strategy."""
    project_id: str
    queries: List[DatabaseQuery] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class Criterion:
    """A single inclusion or exclusion criterion."""
    id: str
    text: str
    category: str  # population, design, outcome, time, etc.
    type: str  # inclusion or exclusion
    mandatory: bool = True
    examples: Optional[List[str]] = None


@dataclass
class ScreeningCriteria:
    """Collection of screening criteria."""
    project_id: str
    inclusion_criteria: List[str] = field(default_factory=list)
    exclusion_criteria: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class ScreeningQuestion:
    """A screening question for title/abstract or full-text review."""
    id: str
    text: str
    applies_to_stage: str  # title_abstract or full_text


@dataclass
class ScreeningChecklist:
    """Collection of screening questions."""
    project_id: str
    questions: List[ScreeningQuestion] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None


@dataclass
class StrategyPackage:
    """Complete research strategy package bundling all artifacts."""
    project_id: str
    context: ProjectContext
    problem_framing: ProblemFraming
    concept_model: ConceptModel
    research_questions: ResearchQuestionSet
    search_concept_blocks: SearchConceptBlocks
    database_query_plan: DatabaseQueryPlan
    screening_criteria: ScreeningCriteria
    screening_checklist: Optional[ScreeningChecklist]
    generated_summary_markdown: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyExportBundle:
    project_id: str
    exported_files: List[str] = field(default_factory=list)  # relative paths under data/<project_id>/export/
    notes: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    status: ApprovalStatus = ApprovalStatus.DRAFT
    model_metadata: Optional[ModelMetadata] = None
    user_notes: Optional[str] = None

